### ISSUE TITLE
As a connector operator, I want that all connectors register themselves at the broker, so that these can be crawled by the Broker

### ISSUE THREAD

**Issue by schoenenberg** [truzzt/ids-basecamp-broker#41]
The FederatedCatalog (Broker) is crawling all Connectors regularly. To be registered as a node at the Connector these have to be stored in the `FederatedCacheNodeStore`.

Some resources: 
- RegistrationHandler (Old Broker): https://github.com/truzzt/metadata-broker-open-core/blob/master/open-broker-common/src/main/java/de/fraunhofer/iais/eis/ids/broker/core/common/persistence/RegistrationHandler.java
- From client/connector perspective (sovity EDC Extension): https://github.com/sovity/edc-extensions/blob/main/extensions/ids-broker-client/src/main/java/de/sovity/extension/broker/service/IdsBrokerServiceImpl.java#L96
- RegisterConnectorMessage: https://github.com/sovity/edc-extensions/blob/main/extensions/ids-broker-client/src/main/java/de/sovity/extension/broker/sender/message/RegisterConnectorMessage.java
- UnregisterConnectorMessage: https://github.com/sovity/edc-extensions/blob/main/extensions/ids-broker-client/src/main/java/de/sovity/extension/broker/sender/message/UnregisterConnectorMessage.java

- IDS Spec: https://github.com/International-Data-Spaces-Association/IDS-G/tree/main/Communication/protocols/multipart#414-connector-registration

**Comment by gjannotti-rl** [comment]
![Planning-for-Register-Broker-Health-Check drawio](https://github.com/truzzt/FederatedCatalog/assets/134397244/b0d00bc4-2931-43c3-ab04-94d1cca53fb4)

**Comment by jannotti-glaucio** [comment]
![image](https://github.com/truzzt/FederatedCatalog/assets/111659831/14220f34-567f-4918-87e5-42508da50cb8)
