### ISSUE TITLE
Update crawler to add status and last crawled

### ISSUE THREAD

**Issue by dhommen** [truzzt/ids-basecamp-broker#67]
Change the crawler success method to update the FederatedCacheNode table with the following values:
- status = online
- lastUpdate = current system date time
- offersCount = number of catalogOffers returned in the catalog

Change the crawler error handler method to update the FederatedCacheNode table node with the following values:
- status = offline
- lastUpdate = current system date time
- offersCount = 0

**Comment by augustocmleal** [comment]
Pull Request #71
